# Generated by Django 5.1.3 on 2024-12-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('name',), 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ('name',), 'verbose_name': 'dish type', 'verbose_name_plural': 'dish types'},
        ),
    ]
